In [1]:
import pandas as pd

In [6]:
kospi_st = pd.read_csv("./데이터/코스피주식(20220).csv", encoding = "euc-kr")
kospi_st.head()

,종목코드,종목명,종가,대비,등락률,시가,고가,저가,거래량,거래대금,시가총액,상장주식수
0,095570,AJ네트웍스,5720,-10,-0.17,5700,5750,5510,112525,631964430,267823527400,46822295
1,006840,AK홀딩스,17200,-150,-0.86,17250,17250,16600,11782,198942500,227858049200,13247561
2,027410,BGF,4305,-40,-0.92,4355,4360,4255,144565,624224765,412060785255,95716791
3,282330,BGF리테일,210500,-1500,-0.71,207000,212500,206500,33874,7124135000,3638262213000,17283906
4,138930,BNK금융지주,6500,-140,-2.11,6560,6580,6470,3097584,20179012670,2118579099000,325935246

In [12]:
kospi_st["회계년도"] = "2022/12"
kospi_st

,종목코드,종목명,종가,대비,등락률,시가,고가,저가,거래량,거래대금,시가총액,상장주식수,회계년도
0,095570,AJ네트웍스,5720,-10,-0.17,5700,5750,5510,112525,631964430,267823527400,46822295,2022/12
1,006840,AK홀딩스,17200,-150,-0.86,17250,17250,16600,11782,198942500,227858049200,13247561,2022/12
2,027410,BGF,4305,-40,-0.92,4355,4360,4255,144565,624224765,412060785255,95716791,2022/12
3,282330,BGF리테일,210500,-1500,-0.71,207000,212500,206500,33874,7124135000,3638262213000,17283906,2022/12
4,138930,BNK금융지주,6500,-140,-2.11,6560,6580,6470,3097584,20179012670,2118579099000,325935246,2022/12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,005010,휴스틸,5070,-20,-0.39,5150,5240,5000,798003,4076704400,284873540250,56188075,2022/12
939,000540,흥국화재,3370,75,2.28,3295,3400,3265,118286,393975725,216497713650,64242645,2022/12
940,000547,흥국화재2우B,16200,-750,-4.42,16850,17050,16200,410,6684300,2488320000,153600,2022/12
941,000545,흥국화재우,6150,-110,-1.76,6450,6450,6150,1079,6685480,4723200000,768000,2022/12
942,003280,흥아해운,1355,-30,-2.17,1385,1430,1330,157217,213966615,325775738145,240424899,2022/12

In [9]:
kospi = pd.read_csv("./데이터/코스피200연결.csv", encoding = "euc-kr")
kospi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20817 entries, 0 to 20816
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   회사명                             20817 non-null  object
 1   거래소코드                           20817 non-null  int64
 2   회계년도                            20817 non-null  object
 3   거래월(*)                          20695 non-null  float64
 4   종가                              20695 non-null  float64
 5   자산(*)(IFRS연결)                   17929 non-null  float64
 6   부채(*)(IFRS연결)                   17929 non-null  float64
 7   당기순이익(손실)(IFRS연결)               17929 non-null  float64
 8   영업활동으로 인한 현금흐름(간접법)(*)(IFRS연결)  17929 non-null  float64
 9   매출액(수익)(*)(IFRS연결)              17929 non-null  float64
 10  비유동자산(*)(IFRS연결)                17929 non-null  float64
 11  매출총이익(손실)(IFRS연결)               17929 non-null  float64
 12  법인세비용(IFRS연결)                   17929 non-null  float64
 13  이자비용(IFRS연결)                    17929 non-null  float64
 14  감가상각비(IFRS연결)                   17929 non-null  float64
 15  유동자산(*)(IFRS연결)                 17929 non-null  float64
 16  유동부채(*)(IFRS연결)                 17929 non-null  float64
 17  현금및현금성자산(*)(IFRS연결)             17929 non-null  float64
dtypes: float64(15), int64(1), object(2)
memory usage: 2.9+ MB

In [11]:
kospi

,회사명,거래소코드,회계년도,거래월(*),종가,자산(*)(IFRS연결),부채(*)(IFRS연결),당기순이익(손실)(IFRS연결),영업활동으로 인한 현금흐름(간접법)(*)(IFRS연결),매출액(수익)(*)(IFRS연결),비유동자산(*)(IFRS연결),매출총이익(손실)(IFRS연결),법인세비용(IFRS연결),이자비용(IFRS연결),감가상각비(IFRS연결),유동자산(*)(IFRS연결),유동부채(*)(IFRS연결),현금및현금성자산(*)(IFRS연결)
0,(주)BNK금융지주,138930,2013/12,1.0,14400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(주)BNK금융지주,138930,2013/12,2.0,15650.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,(주)BNK금융지주,138930,2013/12,3.0,15300.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,(주)BNK금융지주,138930,2013/12,4.0,14500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,(주)BNK금융지주,138930,2013/12,5.0,15700.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20812,효성티앤씨(주),298020,2022/12,8.0,313500.0,4.319879e+09,2.804356e+09,19183248.0,293383061.0,8.882730e+09,2.176811e+09,432144813.0,11475356.0,0.0,14803000.0,2.143068e+09,2.184964e+09,103107215.0
20813,효성티앤씨(주),298020,2022/12,9.0,259000.0,4.319879e+09,2.804356e+09,19183248.0,293383061.0,8.882730e+09,2.176811e+09,432144813.0,11475356.0,0.0,14803000.0,2.143068e+09,2.184964e+09,103107215.0
20814,효성티앤씨(주),298020,2022/12,10.0,261500.0,4.319879e+09,2.804356e+09,19183248.0,293383061.0,8.882730e+09,2.176811e+09,432144813.0,11475356.0,0.0,14803000.0,2.143068e+09,2.184964e+09,103107215.0
20815,효성티앤씨(주),298020,2022/12,11.0,357000.0,4.319879e+09,2.804356e+09,19183248.0,293383061.0,8.882730e+09,2.176811e+09,432144813.0,11475356.0,0.0,14803000.0,2.143068e+09,2.184964e+09,103107215.0
20816,효성티앤씨(주),298020,2022/12,12.0,350000.0,4.319879e+09,2.804356e+09,19183248.0,293383061.0,8.882730e+09,2.176811e+09,432144813.0,11475356.0,0.0,14803000.0,2.143068e+09,2.184964e+09,103107215.0

In [13]:
kospi["거래소코드"].unique()

array([138930,    990, 175330, 105560,  35250,   6280,   5250,   4370,
        47040,   3090,  69620,   3490, 192080,  26960,    150, 138040,
         3850, 282330,  68270,   4170,  31430,  55550,  90430,   2790,
        12750, 383220,  36570,   6260,   1120,   3550,  51900, 373220,
        32640,  51910, 111770,    670,   7310, 271560,   1800, 316140,
          100, 139480,  30000, 185750,  13890,  78930,   7070,  35720,
       323410, 377300,   2380,  30200,  33780, 259960,  47050,   3670,
       103140,  86790,  39130, 352820,   9240,  20000,  14680, 180640,
          880,  10620,  69960,   5440,  57050,   8770, 241590,   4800,
        93370,  81660,   5830, 267250,  16380,  11070,  10120,  10060,
        96770,  10130, 114090,  11780,  73240,    270,  35420, 251270,
         1680,  42660,   6650,   1440,   1230,   6040,  14820, 241560,
        34020, 336260,    210, 375500,  32350,  23530,  20150, 280360,
         4000,   4990,   5300,  11170,   8560,   9900,   6800,   6400,
        28260, 207940,  32830,  18260,  28050,   9150,   5930,  10140,
        16360,  29780,    810,   4490,  19170,   3410, 112610,   1040,
          120,  97950,  20560,  10780, 137310,   5850,  34730,   1740,
       302440, 326030, 402340,  11790, 361610, 285130,  17670,    660,
        10950, 294870,   9540,  42670, 329180, 204320,  11200,   5940,
        79550,  34220,  66570, 271940,  24110,   6360, 381970, 192820,
       120110,  21240, 284740,  39490,   3240,  69260,  28670,   5490,
       178920,     80,  36460,    240,  15760,  52690, 161890, 161390,
        71050,  47810,   8930, 128940, 105630,  18880,   9420, 300720,
        51600,  88350,   9830, 272210,  12450,    720,  86280,  64350,
        12330,  17800,  11210,   5380,   4020,   1450, 298050, 298020],
      dtype=int64)