# OpenApi 란?
 Open API는 다른 서비스나 기관이 제공하는 기능을 사용할 수 있도록 만들어진 인터페이스입니다. 이를 통해 외부 개발자는 해당 서비스의 기능을 활용하여 자신의 애플리케이션 또는 웹사이트에 통합할 수 있습니다.

 예를 들어, Open API를 사용하면 날씨 정보, 지도 데이터, 금융 정보, 영화 정보 등과 같은 다양한 데이터를 가져올 수 있습니다. 이러한 데이터는 외부 서비스에서 제공되며, Open API를 사용하여 해당 데이터에 접근할 수 있습니다.

API는 "Application Programming Interface"의 약자로, 다른 프로그램과 소통하기 위한 규약이나 방법을 의미합니다. Open API는 이 API를 외부 개발자에게 공개하여 사용할 수 있도록 한 것입니다. Open API는 주로 웹 기술과 연계되어 사용되며, HTTP 프로토콜을 통해 요청과 응답을 주고받습니다.

API를 사용하려면 해당 서비스에서 제공하는 API 키가 필요합니다. 이 키를 사용하여 API 요청을 보내면, 서비스 제공자는 요청을 처리하고 필요한 데이터를 응답으로 제공합니다. 응답은 일반적으로 JSON 또는 XML 형식으로 제공되며, 필요한 정보를 추출하여 활용할 수 있습니다.

따라서 Open API는 외부 서비스의 기능과 데이터를 활용하여 개발자가 자신의 애플리케이션에 통합할 수 있는 인터페이스입니다. 이를 통해 다양한 기능을 추가하거나 다른 서비스와 연결하여 보다 다양하고 유용한 애플리케이션을 개발할 수 있습니다.

In [1]:
# JSON(JavaScript Object Notation) 예시 
# {
#   "name": "John Doe",
#   "age": 30,
#   "city": "New York"
# }

In [2]:
# XML(eXtensible Markup Language) 예시
# <book>
#   <title>Harry Potter and the Chamber of Secrets</title>
#   <author>J.K. Rowling</author>
#   <year>1998</year>
# </book>

In [3]:
# 라이브러리 불러오기
import pandas as pd
import statsmodels.api as sm
import numpy as np
import matplotlib.pyplot as plt
import os
import statistics as st
from datetime import datetime, timedelta
import requests
import json

# 경고 메세지 삭제
import warnings
warnings.filterwarnings('ignore')

# 한글 깨짐 방지
import matplotlib.pyplot as plt
plt.rcParams['font.family'] = 'Malgun Gothic'

---
## OpenApi로 영화데이터 가져오기
- https://www.kobis.or.kr/kobisopenapi/homepg/main/main.do

In [4]:
#발급키#
# 001a81c336fe1093a7b65899f0c4e9d4
# 434b7ef51f7c068162c9ccef24f54b28

In [5]:
# 발급 키 입력
yourkey = ''

# 날짜 입력
date_str = ''

url = 'http://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key='+yourkey+'&targetDt='+date_str

res = requests.get()
res
# <Response [200]> => 요청이 성공했음을 나타내는 성공 응답 상태 코드

In [6]:
# 텍스트로 변환
text = res.text
text

'{"boxOfficeResult":{"boxofficeType":"일별 박스오피스","showRange":"20230601~20230601","dailyBoxOfficeList":[{"rnum":"1","rank":"1","rankInten":"0","rankOldAndNew":"OLD","movieCd":"20226411","movieNm":"범죄도시3","openDt":"2023-05-31","salesAmt":"4567997674","salesShare":"90.1","salesInten":"-1682071202","salesChange":"-26.9","salesAcc":"15924391030","audiCnt":"470910","audiInten":"-269934","audiChange":"-36.4","audiAcc":"1695088","scrnCnt":"2262","showCnt":"12629"},{"rnum":"2","rank":"2","rankInten":"0","rankOldAndNew":"OLD","movieCd":"20231496","movieNm":"가디언즈 오브 갤럭시: Volume 3","openDt":"2023-05-03","salesAmt":"128572123","salesShare":"2.5","salesInten":"-33625099","salesChange":"-20.7","salesAcc":"41687142801","audiCnt":"13100","audiInten":"-7663","audiChange":"-36.9","audiAcc":"3949553","scrnCnt":"623","showCnt":"1338"},{"rnum":"3","rank":"3","rankInten":"0","rankOldAndNew":"OLD","movieCd":"20231592","movieNm":"분노의 질주: 라이드 오어 다이","openDt":"2023-05-17","salesAmt":"106884872","salesShare":"2.1","salesInten":"-34195906","salesChange":"-24.2","salesAcc":"17101709632","audiCnt":"11060","audiInten":"-7034","audiChange":"-38.9","audiAcc":"1635995","scrnCnt":"669","showCnt":"1573"},{"rnum":"4","rank":"4","rankInten":"0","rankOldAndNew":"OLD","movieCd":"20231839","movieNm":"인어공주","openDt":"2023-05-24","salesAmt":"78961459","salesShare":"1.6","salesInten":"-30884757","salesChange":"-28.1","salesAcc":"5157612970","audiCnt":"8180","audiInten":"-6241","audiChange":"-43.3","audiAcc":"496135","scrnCnt":"589","showCnt":"1099"},{"rnum":"5","rank":"5","rankInten":"0","rankOldAndNew":"OLD","movieCd":"20090860","movieNm":"포켓 몬스터 DP: 아르세우스 초극의 시공으로","openDt":"2009-12-24","salesAmt":"38235132","salesShare":"0.8","salesInten":"-73393731","salesChange":"-65.7","salesAcc":"2391751995","audiCnt":"4233","audiInten":"-9046","audiChange":"-68.1","audiAcc":"355520","scrnCnt":"446","showCnt":"607"},{"rnum":"6","rank":"6","rankInten":"0","rankOldAndNew":"OLD","movieCd":"20231677","movieNm":"남은 인생 10년","openDt":"2023-05-24","salesAmt":"30796900","salesShare":"0.6","salesInten":"3269000","salesChange":"11.9","salesAcc":"743577800","audiCnt":"2822","audiInten":"-641","audiChange":"-18.5","audiAcc":"69846","scrnCnt":"99","showCnt":"185"},{"rnum":"7","rank":"7","rankInten":"2","rankOldAndNew":"OLD","movieCd":"20231603","movieNm":"라이드 온","openDt":"2023-05-31","salesAmt":"16528200","salesShare":"0.3","salesInten":"5470301","salesChange":"49.5","salesAcc":"47053099","audiCnt":"2006","audiInten":"634","audiChange":"46.2","audiAcc":"5541","scrnCnt":"89","showCnt":"122"},{"rnum":"8","rank":"8","rankInten":"4","rankOldAndNew":"OLD","movieCd":"20231348","movieNm":"극장판 짱구는 못말려: 동물소환 닌자 배꼽수비대","openDt":"2023-05-04","salesAmt":"12998075","salesShare":"0.3","salesInten":"3682158","salesChange":"39.5","salesAcc":"6844103900","audiCnt":"1602","audiInten":"393","audiChange":"32.5","audiAcc":"690348","scrnCnt":"109","showCnt":"131"},{"rnum":"9","rank":"9","rankInten":"-2","rankOldAndNew":"OLD","movieCd":"20226270","movieNm":"스즈메의 문단속","openDt":"2023-03-08","salesAmt":"15708807","salesShare":"0.3","salesInten":"-8128642","salesChange":"-34.1","salesAcc":"56438700242","audiCnt":"1560","audiInten":"-1474","audiChange":"-48.6","audiAcc":"5503654","scrnCnt":"110","showCnt":"125"},{"rnum":"10","rank":"10","rankInten":"1","rankOldAndNew":"OLD","movieCd":"20219997","movieNm":"드림팰리스","openDt":"2023-05-31","salesAmt":"7910899","salesShare":"0.2","salesInten":"-1695101","salesChange":"-17.6","salesAcc":"26447899","audiCnt":"1118","audiInten":"-174","audiChange":"-13.5","audiAcc":"3429","scrnCnt":"75","showCnt":"102"}]}}'

In [7]:
# 데이터 추출
movie = json.loads()
movie

{'boxOfficeResult': {'boxofficeType': '일별 박스오피스',
  'showRange': '20230601~20230601',
  'dailyBoxOfficeList': [{'rnum': '1',
    'rank': '1',
    'rankInten': '0',
    'rankOldAndNew': 'OLD',
    'movieCd': '20226411',
    'movieNm': '범죄도시3',
    'openDt': '2023-05-31',
    'salesAmt': '4567997674',
    'salesShare': '90.1',
    'salesInten': '-1682071202',
    'salesChange': '-26.9',
    'salesAcc': '15924391030',
    'audiCnt': '470910',
    'audiInten': '-269934',
    'audiChange': '-36.4',
    'audiAcc': '1695088',
    'scrnCnt': '2262',
    'showCnt': '12629'},
   {'rnum': '2',
    'rank': '2',
    'rankInten': '0',
    'rankOldAndNew': 'OLD',
    'movieCd': '20231496',
    'movieNm': '가디언즈 오브 갤럭시: Volume 3',
    'openDt': '2023-05-03',
    'salesAmt': '128572123',
    'salesShare': '2.5',
    'salesInten': '-33625099',
    'salesChange': '-20.7',
    'salesAcc': '41687142801',
    'audiCnt': '13100',
    'audiInten': '-7663',
    'audiChange': '-36.9',
    'audiAcc': '3949553',
    'scrnCnt': '623',
    'showCnt': '1338'},
   {'rnum': '3',
    'rank': '3',
    'rankInten': '0',
    'rankOldAndNew': 'OLD',
    'movieCd': '20231592',
    'movieNm': '분노의 질주: 라이드 오어 다이',
    'openDt': '2023-05-17',
    'salesAmt': '106884872',
    'salesShare': '2.1',
    'salesInten': '-34195906',
    'salesChange': '-24.2',
    'salesAcc': '17101709632',
    'audiCnt': '11060',
    'audiInten': '-7034',
    'audiChange': '-38.9',
    'audiAcc': '1635995',
    'scrnCnt': '669',
    'showCnt': '1573'},
   {'rnum': '4',
    'rank': '4',
    'rankInten': '0',
    'rankOldAndNew': 'OLD',
    'movieCd': '20231839',
    'movieNm': '인어공주',
    'openDt': '2023-05-24',
    'salesAmt': '78961459',
    'salesShare': '1.6',
    'salesInten': '-30884757',
    'salesChange': '-28.1',
    'salesAcc': '5157612970',
    'audiCnt': '8180',
    'audiInten': '-6241',
    'audiChange': '-43.3',
    'audiAcc': '496135',
    'scrnCnt': '589',
    'showCnt': '1099'},
   {'rnum': '5',
    'rank': '5',
    'rankInten': '0',
    'rankOldAndNew': 'OLD',
    'movieCd': '20090860',
    'movieNm': '포켓 몬스터 DP: 아르세우스 초극의 시공으로',
    'openDt': '2009-12-24',
    'salesAmt': '38235132',
    'salesShare': '0.8',
    'salesInten': '-73393731',
    'salesChange': '-65.7',
    'salesAcc': '2391751995',
    'audiCnt': '4233',
    'audiInten': '-9046',
    'audiChange': '-68.1',
    'audiAcc': '355520',
    'scrnCnt': '446',
    'showCnt': '607'},
   {'rnum': '6',
    'rank': '6',
    'rankInten': '0',
    'rankOldAndNew': 'OLD',
    'movieCd': '20231677',
    'movieNm': '남은 인생 10년',
    'openDt': '2023-05-24',
    'salesAmt': '30796900',
    'salesShare': '0.6',
    'salesInten': '3269000',
    'salesChange': '11.9',
    'salesAcc': '743577800',
    'audiCnt': '2822',
    'audiInten': '-641',
    'audiChange': '-18.5',
    'audiAcc': '69846',
    'scrnCnt': '99',
    'showCnt': '185'},
   {'rnum': '7',
    'rank': '7',
    'rankInten': '2',
    'rankOldAndNew': 'OLD',
    'movieCd': '20231603',
    'movieNm': '라이드 온',
    'openDt': '2023-05-31',
    'salesAmt': '16528200',
    'salesShare': '0.3',
    'salesInten': '5470301',
    'salesChange': '49.5',
    'salesAcc': '47053099',
    'audiCnt': '2006',
    'audiInten': '634',
    'audiChange': '46.2',
    'audiAcc': '5541',
    'scrnCnt': '89',
    'showCnt': '122'},
   {'rnum': '8',
    'rank': '8',
    'rankInten': '4',
    'rankOldAndNew': 'OLD',
    'movieCd': '20231348',
    'movieNm': '극장판 짱구는 못말려: 동물소환 닌자 배꼽수비대',
    'openDt': '2023-05-04',
    'salesAmt': '12998075',
    'salesShare': '0.3',
    'salesInten': '3682158',
    'salesChange': '39.5',
    'salesAcc': '6844103900',
    'audiCnt': '1602',
    'audiInten': '393',
    'audiChange': '32.5',
    'audiAcc': '690348',
    'scrnCnt': '109',
    'showCnt': '131'},
   {'rnum': '9',
    'rank': '9',
    'rankInten': '-2',
    'rankOldAndNew': 'OLD',
    'movieCd': '20226270',
    'movieNm': '스즈메의 문단속',
    'openDt': '2023-03-08',
    'salesAmt': '15708807',
    'salesShare': '0.3',
    'salesInten': '-8128642',
    'salesChange': '-34.1',
    'salesAcc': '56438700242',
    'audiCnt': '1560',
    'audiInten': '-1474',
    'audiChange': '-48.6',
    'audiAcc': '5503654',
    'scrnCnt': '110',
    'showCnt': '125'},
   {'rnum': '10',
    'rank': '10',
    'rankInten': '1',
    'rankOldAndNew': 'OLD',
    'movieCd': '20219997',
    'movieNm': '드림팰리스',
    'openDt': '2023-05-31',
    'salesAmt': '7910899',
    'salesShare': '0.2',
    'salesInten': '-1695101',
    'salesChange': '-17.6',
    'salesAcc': '26447899',
    'audiCnt': '1118',
    'audiInten': '-174',
    'audiChange': '-13.5',
    'audiAcc': '3429',
    'scrnCnt': '75',
    'showCnt': '102'}]}}

In [8]:
# 일별 박스오피스에서 showRange의 값 20230601~20230601 추출해보기

'20230601~20230601'

In [9]:
# dailyBoxOfficeList의 값 모두 추출해보기

[{'rnum': '1',
  'rank': '1',
  'rankInten': '0',
  'rankOldAndNew': 'OLD',
  'movieCd': '20226411',
  'movieNm': '범죄도시3',
  'openDt': '2023-05-31',
  'salesAmt': '4567997674',
  'salesShare': '90.1',
  'salesInten': '-1682071202',
  'salesChange': '-26.9',
  'salesAcc': '15924391030',
  'audiCnt': '470910',
  'audiInten': '-269934',
  'audiChange': '-36.4',
  'audiAcc': '1695088',
  'scrnCnt': '2262',
  'showCnt': '12629'},
 {'rnum': '2',
  'rank': '2',
  'rankInten': '0',
  'rankOldAndNew': 'OLD',
  'movieCd': '20231496',
  'movieNm': '가디언즈 오브 갤럭시: Volume 3',
  'openDt': '2023-05-03',
  'salesAmt': '128572123',
  'salesShare': '2.5',
  'salesInten': '-33625099',
  'salesChange': '-20.7',
  'salesAcc': '41687142801',
  'audiCnt': '13100',
  'audiInten': '-7663',
  'audiChange': '-36.9',
  'audiAcc': '3949553',
  'scrnCnt': '623',
  'showCnt': '1338'},
 {'rnum': '3',
  'rank': '3',
  'rankInten': '0',
  'rankOldAndNew': 'OLD',
  'movieCd': '20231592',
  'movieNm': '분노의 질주: 라이드 오어 다이',
  'openDt': '2023-05-17',
  'salesAmt': '106884872',
  'salesShare': '2.1',
  'salesInten': '-34195906',
  'salesChange': '-24.2',
  'salesAcc': '17101709632',
  'audiCnt': '11060',
  'audiInten': '-7034',
  'audiChange': '-38.9',
  'audiAcc': '1635995',
  'scrnCnt': '669',
  'showCnt': '1573'},
 {'rnum': '4',
  'rank': '4',
  'rankInten': '0',
  'rankOldAndNew': 'OLD',
  'movieCd': '20231839',
  'movieNm': '인어공주',
  'openDt': '2023-05-24',
  'salesAmt': '78961459',
  'salesShare': '1.6',
  'salesInten': '-30884757',
  'salesChange': '-28.1',
  'salesAcc': '5157612970',
  'audiCnt': '8180',
  'audiInten': '-6241',
  'audiChange': '-43.3',
  'audiAcc': '496135',
  'scrnCnt': '589',
  'showCnt': '1099'},
 {'rnum': '5',
  'rank': '5',
  'rankInten': '0',
  'rankOldAndNew': 'OLD',
  'movieCd': '20090860',
  'movieNm': '포켓 몬스터 DP: 아르세우스 초극의 시공으로',
  'openDt': '2009-12-24',
  'salesAmt': '38235132',
  'salesShare': '0.8',
  'salesInten': '-73393731',
  'salesChange': '-65.7',
  'salesAcc': '2391751995',
  'audiCnt': '4233',
  'audiInten': '-9046',
  'audiChange': '-68.1',
  'audiAcc': '355520',
  'scrnCnt': '446',
  'showCnt': '607'},
 {'rnum': '6',
  'rank': '6',
  'rankInten': '0',
  'rankOldAndNew': 'OLD',
  'movieCd': '20231677',
  'movieNm': '남은 인생 10년',
  'openDt': '2023-05-24',
  'salesAmt': '30796900',
  'salesShare': '0.6',
  'salesInten': '3269000',
  'salesChange': '11.9',
  'salesAcc': '743577800',
  'audiCnt': '2822',
  'audiInten': '-641',
  'audiChange': '-18.5',
  'audiAcc': '69846',
  'scrnCnt': '99',
  'showCnt': '185'},
 {'rnum': '7',
  'rank': '7',
  'rankInten': '2',
  'rankOldAndNew': 'OLD',
  'movieCd': '20231603',
  'movieNm': '라이드 온',
  'openDt': '2023-05-31',
  'salesAmt': '16528200',
  'salesShare': '0.3',
  'salesInten': '5470301',
  'salesChange': '49.5',
  'salesAcc': '47053099',
  'audiCnt': '2006',
  'audiInten': '634',
  'audiChange': '46.2',
  'audiAcc': '5541',
  'scrnCnt': '89',
  'showCnt': '122'},
 {'rnum': '8',
  'rank': '8',
  'rankInten': '4',
  'rankOldAndNew': 'OLD',
  'movieCd': '20231348',
  'movieNm': '극장판 짱구는 못말려: 동물소환 닌자 배꼽수비대',
  'openDt': '2023-05-04',
  'salesAmt': '12998075',
  'salesShare': '0.3',
  'salesInten': '3682158',
  'salesChange': '39.5',
  'salesAcc': '6844103900',
  'audiCnt': '1602',
  'audiInten': '393',
  'audiChange': '32.5',
  'audiAcc': '690348',
  'scrnCnt': '109',
  'showCnt': '131'},
 {'rnum': '9',
  'rank': '9',
  'rankInten': '-2',
  'rankOldAndNew': 'OLD',
  'movieCd': '20226270',
  'movieNm': '스즈메의 문단속',
  'openDt': '2023-03-08',
  'salesAmt': '15708807',
  'salesShare': '0.3',
  'salesInten': '-8128642',
  'salesChange': '-34.1',
  'salesAcc': '56438700242',
  'audiCnt': '1560',
  'audiInten': '-1474',
  'audiChange': '-48.6',
  'audiAcc': '5503654',
  'scrnCnt': '110',
  'showCnt': '125'},
 {'rnum': '10',
  'rank': '10',
  'rankInten': '1',
  'rankOldAndNew': 'OLD',
  'movieCd': '20219997',
  'movieNm': '드림팰리스',
  'openDt': '2023-05-31',
  'salesAmt': '7910899',
  'salesShare': '0.2',
  'salesInten': '-1695101',
  'salesChange': '-17.6',
  'salesAcc': '26447899',
  'audiCnt': '1118',
  'audiInten': '-174',
  'audiChange': '-13.5',
  'audiAcc': '3429',
  'scrnCnt': '75',
  'showCnt': '102'}]

In [10]:
# 빈 리스트 생성
movie_list
 #박스오피스 일자 추출
boxoffice = 

for i in movie['boxOfficeResult']['dailyBoxOfficeList']:
    movie_list.append([boxoffice, i['movieNm'],i['movieCd'],i['audiCnt'],i['audiAcc']
                           ,i['openDt'],i['salesAmt'],i['salesAcc']
                           ,i['scrnCnt'],i['showCnt'],i['rank'],i['rankOldAndNew']])

movie_list

[['20230601~20230601',
  '범죄도시3',
  '20226411',
  '470910',
  '1695088',
  '2023-05-31',
  '4567997674',
  '15924391030',
  '2262',
  '12629',
  '1',
  'OLD'],
 ['20230601~20230601',
  '가디언즈 오브 갤럭시: Volume 3',
  '20231496',
  '13100',
  '3949553',
  '2023-05-03',
  '128572123',
  '41687142801',
  '623',
  '1338',
  '2',
  'OLD'],
 ['20230601~20230601',
  '분노의 질주: 라이드 오어 다이',
  '20231592',
  '11060',
  '1635995',
  '2023-05-17',
  '106884872',
  '17101709632',
  '669',
  '1573',
  '3',
  'OLD'],
 ['20230601~20230601',
  '인어공주',
  '20231839',
  '8180',
  '496135',
  '2023-05-24',
  '78961459',
  '5157612970',
  '589',
  '1099',
  '4',
  'OLD'],
 ['20230601~20230601',
  '포켓 몬스터 DP: 아르세우스 초극의 시공으로',
  '20090860',
  '4233',
  '355520',
  '2009-12-24',
  '38235132',
  '2391751995',
  '446',
  '607',
  '5',
  'OLD'],
 ['20230601~20230601',
  '남은 인생 10년',
  '20231677',
  '2822',
  '69846',
  '2023-05-24',
  '30796900',
  '743577800',
  '99',
  '185',
  '6',
  'OLD'],
 ['20230601~20230601',
  '라이드 온',
  '20231603',
  '2006',
  '5541',
  '2023-05-31',
  '16528200',
  '47053099',
  '89',
  '122',
  '7',
  'OLD'],
 ['20230601~20230601',
  '극장판 짱구는 못말려: 동물소환 닌자 배꼽수비대',
  '20231348',
  '1602',
  '690348',
  '2023-05-04',
  '12998075',
  '6844103900',
  '109',
  '131',
  '8',
  'OLD'],
 ['20230601~20230601',
  '스즈메의 문단속',
  '20226270',
  '1560',
  '5503654',
  '2023-03-08',
  '15708807',
  '56438700242',
  '110',
  '125',
  '9',
  'OLD'],
 ['20230601~20230601',
  '드림팰리스',
  '20219997',
  '1118',
  '3429',
  '2023-05-31',
  '7910899',
  '26447899',
  '75',
  '102',
  '10',
  'OLD']]

In [11]:
# 데이터프레임으로 변경
data = pd.DataFrame()
data

,0,1,2,3,4,5,6,7,8,9,10,11
0,20230601~20230601,범죄도시3,20226411,470910,1695088,2023-05-31,4567997674,15924391030,2262,12629,1,OLD
1,20230601~20230601,가디언즈 오브 갤럭시: Volume 3,20231496,13100,3949553,2023-05-03,128572123,41687142801,623,1338,2,OLD
2,20230601~20230601,분노의 질주: 라이드 오어 다이,20231592,11060,1635995,2023-05-17,106884872,17101709632,669,1573,3,OLD
3,20230601~20230601,인어공주,20231839,8180,496135,2023-05-24,78961459,5157612970,589,1099,4,OLD
4,20230601~20230601,포켓 몬스터 DP: 아르세우스 초극의 시공으로,20090860,4233,355520,2009-12-24,38235132,2391751995,446,607,5,OLD
5,20230601~20230601,남은 인생 10년,20231677,2822,69846,2023-05-24,30796900,743577800,99,185,6,OLD
6,20230601~20230601,라이드 온,20231603,2006,5541,2023-05-31,16528200,47053099,89,122,7,OLD
7,20230601~20230601,극장판 짱구는 못말려: 동물소환 닌자 배꼽수비대,20231348,1602,690348,2023-05-04,12998075,6844103900,109,131,8,OLD
8,20230601~20230601,스즈메의 문단속,20226270,1560,5503654,2023-03-08,15708807,56438700242,110,125,9,OLD
9,20230601~20230601,드림팰리스,20219997,1118,3429,2023-05-31,7910899,26447899,75,102,10,OLD

In [12]:
# 컬럼명 변경 - '날짜','영화명','대표코드','개봉일 관객수','누적관객수','개봉일','개봉일 매출액','누적매출액','스크린수','상영된 횟수','순위','신규진입여부'

,날짜,영화명,대표코드,개봉일 관객수,누적관객수,개봉일,개봉일 매출액,누적매출액,스크린수,상영된 횟수,순위,신규진입여부
0,20230601~20230601,범죄도시3,20226411,470910,1695088,2023-05-31,4567997674,15924391030,2262,12629,1,OLD
1,20230601~20230601,가디언즈 오브 갤럭시: Volume 3,20231496,13100,3949553,2023-05-03,128572123,41687142801,623,1338,2,OLD
2,20230601~20230601,분노의 질주: 라이드 오어 다이,20231592,11060,1635995,2023-05-17,106884872,17101709632,669,1573,3,OLD
3,20230601~20230601,인어공주,20231839,8180,496135,2023-05-24,78961459,5157612970,589,1099,4,OLD
4,20230601~20230601,포켓 몬스터 DP: 아르세우스 초극의 시공으로,20090860,4233,355520,2009-12-24,38235132,2391751995,446,607,5,OLD
5,20230601~20230601,남은 인생 10년,20231677,2822,69846,2023-05-24,30796900,743577800,99,185,6,OLD
6,20230601~20230601,라이드 온,20231603,2006,5541,2023-05-31,16528200,47053099,89,122,7,OLD
7,20230601~20230601,극장판 짱구는 못말려: 동물소환 닌자 배꼽수비대,20231348,1602,690348,2023-05-04,12998075,6844103900,109,131,8,OLD
8,20230601~20230601,스즈메의 문단속,20226270,1560,5503654,2023-03-08,15708807,56438700242,110,125,9,OLD
9,20230601~20230601,드림팰리스,20219997,1118,3429,2023-05-31,7910899,26447899,75,102,10,OLD

---
## 기간을 설정하고 추출해보기

In [13]:
date = datetime(2023, 1, 1)
date

datetime.datetime(2023, 1, 1, 0, 0)

In [14]:
# 방법1
# strftime사용 후 replace로 '-' 제거하기

'20230101'

In [15]:
# 방법2 
# split() 문자열을 이쁘게 나눠서 리스트로 만들때 사용하는 함수

'20230101'

In [16]:
# 날짜를 문자열로 변환하는 함수
def date_string(date):
    date_list = str(date).split()[0].split('-')
    date_str = date_list[0]+date_list[1]+date_list[2]
    return date_str

yourkey='001a81c336fe1093a7b65899f0c4e9d4' #(키 넣어주시면 됩니다!)

#원하는 날짜 +1 해주세요. 2022년 전체를 하고싶다면 (2023,1,1) (날짜 수정해주시면 됩니다!)
date = datetime(2023,4,1)
date_str = date_string(date)

# 2022년 1월1일까지만 할것이다 (날짜 수정해주시면 됩니다!)
while date_str != '20230301':
    date = date - timedelta(days=1)
    date_str = date_string(date)
    # print(date_str)
    
    url = 'http://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key='+yourkey+'&targetDt='+date_str
    res = requests.get(url)
    text= res.text

    movie = json.loads(text)

    # 빈 리스트 생성
    movie_list = []

    boxoffice=movie['boxOfficeResult']['showRange'] #박스오피스 일자 추출

    for i in movie['boxOfficeResult']['dailyBoxOfficeList']:
        movie_list.append([boxoffice, i['movieNm'],i['movieCd'],i['audiCnt'],i['audiAcc'],i['openDt']
                           ,i['salesAmt'],i['salesAcc'],i['scrnCnt'],i['showCnt'],i['rank'],i['rankOldAndNew']])

    # 파일 이름 변경하는 곳 (파일이름 수정해주시면 됩니다!)
    data = pd.DataFrame(movie_list)
    
    # mode : 파일을 열 때의 모드, 'a'는 append(추가) 모드로, 기존 파일에 내용을 추가할 때 사용
    # encoding : 파일의 인코딩 방식을 지정합니다. 'utf-8'은 유니코드 문자를 지원하는 인코딩 방식으로, 다양한 언어의 문자를 처리
    # index : CSV 파일에 인덱스를 저장하지 않도록 설정, False는 인덱스가 저장되지 않음
    data.to_csv("2023.03_movie.csv", mode='a', encoding='utf-8', index=False)

In [17]:
# 저장된 데이터 불러오기

,0,1,2,3,4,5,6,7,8,9,10,11
0,20230331~20230331,스즈메의 문단속,20226270,85235,3288584,2023-03-08,874523296,34212674348,1302,4978,1,OLD
1,20230331~20230331,던전 앤 드래곤: 도적들의 명예,20226410,26076,83760,2023-03-29,269380282,794254727,1091,3576,2,OLD
2,20230331~20230331,더 퍼스트 슬램덩크,20228555,11053,4330206,2023-01-04,114782228,44616297739,553,1149,3,OLD
3,20230331~20230331,웅남이,20210544,10612,231631,2023-03-22,96145473,2103958816,626,1729,4,OLD
4,20230331~20230331,소울메이트,20197654,3524,204122,2023-03-15,33277388,1981732434,348,572,5,OLD
...,...,...,...,...,...,...,...,...,...,...,...,...
676,20230301~20230301,서치 2,20239573,35839,276983,2023-02-22,366486430,2709150132,674,1612,6,OLD
677,20230301~20230301,카운트,20193706,28800,302160,2023-02-22,288902686,2894639011,716,1768,7,OLD
678,20230301~20230301,마루이 비디오,20202026,12475,134032,2023-02-22,137181600,1357193900,233,518,8,OLD
679,20230301~20230301,두다다쿵: 후후섬의 비밀,20210684,9786,100067,2023-02-15,90252424,908055449,291,355,9,OLD
680,20230301~20230301,에브리씽 에브리웨어 올 앳 원스+,20230340,8432,10679,2023-03-01,88743920,110302720,199,269,10,OLD

In [18]:
# 컬럼명 변경

,날짜,영화명,대표코드,개봉일 관객수,누적관객수,개봉일,개봉일 매출액,누적매출액,스크린수,상영된 횟수,순위,신규진입여부
0,20230331~20230331,스즈메의 문단속,20226270,85235,3288584,2023-03-08,874523296,34212674348,1302,4978,1,OLD
1,20230331~20230331,던전 앤 드래곤: 도적들의 명예,20226410,26076,83760,2023-03-29,269380282,794254727,1091,3576,2,OLD
2,20230331~20230331,더 퍼스트 슬램덩크,20228555,11053,4330206,2023-01-04,114782228,44616297739,553,1149,3,OLD
3,20230331~20230331,웅남이,20210544,10612,231631,2023-03-22,96145473,2103958816,626,1729,4,OLD
4,20230331~20230331,소울메이트,20197654,3524,204122,2023-03-15,33277388,1981732434,348,572,5,OLD
...,...,...,...,...,...,...,...,...,...,...,...,...
676,20230301~20230301,서치 2,20239573,35839,276983,2023-02-22,366486430,2709150132,674,1612,6,OLD
677,20230301~20230301,카운트,20193706,28800,302160,2023-02-22,288902686,2894639011,716,1768,7,OLD
678,20230301~20230301,마루이 비디오,20202026,12475,134032,2023-02-22,137181600,1357193900,233,518,8,OLD
679,20230301~20230301,두다다쿵: 후후섬의 비밀,20210684,9786,100067,2023-02-15,90252424,908055449,291,355,9,OLD
680,20230301~20230301,에브리씽 에브리웨어 올 앳 원스+,20230340,8432,10679,2023-03-01,88743920,110302720,199,269,10,OLD

In [19]:
# 정보 추출

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 681 entries, 0 to 680
Data columns (total 12 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   날짜       681 non-null    object
 1   영화명      681 non-null    object
 2   대표코드     681 non-null    int64
 3   개봉일 관객수  681 non-null    int64
 4   누적관객수    681 non-null    int64
 5   개봉일      681 non-null    object
 6   개봉일 매출액  681 non-null    int64
 7   누적매출액    681 non-null    int64
 8   스크린수     681 non-null    int64
 9   상영된 횟수   681 non-null    int64
 10  순위       681 non-null    int64
 11  신규진입여부   681 non-null    object
dtypes: int64(8), object(4)
memory usage: 64.0+ KB

In [20]:
# 날짜 8자리만 추출

,날짜,영화명,대표코드,개봉일 관객수,누적관객수,개봉일,개봉일 매출액,누적매출액,스크린수,상영된 횟수,순위,신규진입여부
0,20230331,스즈메의 문단속,20226270,85235,3288584,2023-03-08,874523296,34212674348,1302,4978,1,OLD
1,20230331,던전 앤 드래곤: 도적들의 명예,20226410,26076,83760,2023-03-29,269380282,794254727,1091,3576,2,OLD
2,20230331,더 퍼스트 슬램덩크,20228555,11053,4330206,2023-01-04,114782228,44616297739,553,1149,3,OLD
3,20230331,웅남이,20210544,10612,231631,2023-03-22,96145473,2103958816,626,1729,4,OLD
4,20230331,소울메이트,20197654,3524,204122,2023-03-15,33277388,1981732434,348,572,5,OLD
...,...,...,...,...,...,...,...,...,...,...,...,...
676,20230301,서치 2,20239573,35839,276983,2023-02-22,366486430,2709150132,674,1612,6,OLD
677,20230301,카운트,20193706,28800,302160,2023-02-22,288902686,2894639011,716,1768,7,OLD
678,20230301,마루이 비디오,20202026,12475,134032,2023-02-22,137181600,1357193900,233,518,8,OLD
679,20230301,두다다쿵: 후후섬의 비밀,20210684,9786,100067,2023-02-15,90252424,908055449,291,355,9,OLD
680,20230301,에브리씽 에브리웨어 올 앳 원스+,20230340,8432,10679,2023-03-01,88743920,110302720,199,269,10,OLD

In [21]:
# 1. 날짜 순으로 내림차순 정렬
# 2. 데이터 중 문제가 있는 데이터 제거
# 3. 날짜 - 데이트타임형태로 변경
# 4. 인덱스 초기화

,날짜,영화명,대표코드,개봉일 관객수,누적관객수,개봉일,개봉일 매출액,누적매출액,스크린수,상영된 횟수,순위,신규진입여부
0,2023-03-01,에브리씽 에브리웨어 올 앳 원스+,20230340,8432,10679,2023-03-01,88743920,110302720,199,269,10,OLD
1,2023-03-01,마루이 비디오,20202026,12475,134032,2023-02-22,137181600,1357193900,233,518,8,OLD
2,2023-03-01,카운트,20193706,28800,302160,2023-02-22,288902686,2894639011,716,1768,7,OLD
3,2023-03-01,서치 2,20239573,35839,276983,2023-02-22,366486430,2709150132,674,1612,6,OLD
4,2023-03-01,멍뭉이,20227684,39108,40740,2023-03-01,373426620,390074620,593,1656,5,OLD
...,...,...,...,...,...,...,...,...,...,...,...,...
615,2023-03-31,에브리씽 에브리웨어 올 앳 원스+,20230340,1606,97919,2023-03-01,16238295,1007796363,97,128,8,OLD
616,2023-03-31,해피 투게더,20080269,1574,47222,1998-08-22,17072643,436614106,120,232,9,OLD
617,2023-03-31,멍뭉이,20227684,1538,178067,2023-03-01,13875797,1672858392,21,29,10,OLD
618,2023-03-31,스즈메의 문단속,20226270,85235,3288584,2023-03-08,874523296,34212674348,1302,4978,1,OLD
619,2023-03-31,스즈메의 문단속,20226270,85235,3288584,2023-03-08,874523296,34212674348,1302,4978,1,OLD

---
## 공공 Openapi 데이터 가져오기
- 한국환경공단_에어코리아_대기오염통계 현황
- https://www.data.go.kr/iim/api/selectAPIAcountView.do

In [22]:
# url 입력
yourkey = '1UQZTnyGMC0LoiusOGYLU6SJfaOJXqz2t6ZUUw5ZKDIxOzFGGkhLlW3bHkT5vaShQrUqJrZRPJucnWmszUsVJQ%3D%3D'

url = 'https://apis.data.go.kr/B552584/ArpltnStatsSvc/getMsrstnAcctoRMmrg?serviceKey='+yourkey+'&returnType=json&numOfRows=100&pageNo=1&inqBginMm=202205&inqEndMm=202305&msrstnName=%EA%B0%95%EB%82%A8%EA%B5%AC'

# url 불러오기
response = requests.get(url)

#데이터 값 출력해보기
contents = response.text
contents

'{"response":{"body":{"totalCount":13,"items":[{"msurMm":"2022-05","so2Value":".003","coValue":".3","msrstnName":"강남구","pm10Value":"31","no2Value":".016","o3Value":".051","pm25Value":"16"},{"msurMm":"2022-06","so2Value":".003","coValue":".3","msrstnName":"강남구","pm10Value":"22","no2Value":".016","o3Value":".038","pm25Value":"12"},{"msurMm":"2022-07","so2Value":".003","coValue":".3","msrstnName":"강남구","pm10Value":"26","no2Value":".017","o3Value":".039","pm25Value":"17"},{"msurMm":"2022-08","so2Value":".003","coValue":".3","msrstnName":"강남구","pm10Value":"21","no2Value":".017","o3Value":".033","pm25Value":"12"},{"msurMm":"2022-09","so2Value":".003","coValue":".3","msrstnName":"강남구","pm10Value":"23","no2Value":".02","o3Value":".032","pm25Value":"12"},{"msurMm":"2022-10","so2Value":".003","coValue":".4","msrstnName":"강남구","pm10Value":"26","no2Value":".024","o3Value":".024","pm25Value":"14"},{"msurMm":"2022-11","so2Value":".003","coValue":".5","msrstnName":"강남구","pm10Value":"39","no2Value":".031","o3Value":".019","pm25Value":"22"},{"msurMm":"2022-12","so2Value":".003","coValue":".5","msrstnName":"강남구","pm10Value":"37","no2Value":".029","o3Value":".016","pm25Value":"18"},{"msurMm":"2023-01","so2Value":".003","coValue":".5","msrstnName":"강남구","pm10Value":"46","no2Value":".031","o3Value":".017","pm25Value":"25"},{"msurMm":"2023-02","so2Value":".003","coValue":".5","msrstnName":"강남구","pm10Value":"46","no2Value":".032","o3Value":".023","pm25Value":"28"},{"msurMm":"2023-03","so2Value":".003","coValue":".5","msrstnName":"강남구","pm10Value":"65","no2Value":".031","o3Value":".034","pm25Value":"29"},{"msurMm":"2023-04","so2Value":".003","coValue":".4","msrstnName":"강남구","pm10Value":"60","no2Value":".02","o3Value":".04","pm25Value":"19"},{"msurMm":"2023-05","so2Value":".003","coValue":".3","msrstnName":"강남구","pm10Value":"38","no2Value":".02","o3Value":".043","pm25Value":"18"}],"pageNo":1,"numOfRows":100},"header":{"resultMsg":"NORMAL_CODE","resultCode":"00"}}}'

In [23]:
json.loads(contents)

{'response': {'body': {'totalCount': 13,
   'items': [{'msurMm': '2022-05',
     'so2Value': '.003',
     'coValue': '.3',
     'msrstnName': '강남구',
     'pm10Value': '31',
     'no2Value': '.016',
     'o3Value': '.051',
     'pm25Value': '16'},
    {'msurMm': '2022-06',
     'so2Value': '.003',
     'coValue': '.3',
     'msrstnName': '강남구',
     'pm10Value': '22',
     'no2Value': '.016',
     'o3Value': '.038',
     'pm25Value': '12'},
    {'msurMm': '2022-07',
     'so2Value': '.003',
     'coValue': '.3',
     'msrstnName': '강남구',
     'pm10Value': '26',
     'no2Value': '.017',
     'o3Value': '.039',
     'pm25Value': '17'},
    {'msurMm': '2022-08',
     'so2Value': '.003',
     'coValue': '.3',
     'msrstnName': '강남구',
     'pm10Value': '21',
     'no2Value': '.017',
     'o3Value': '.033',
     'pm25Value': '12'},
    {'msurMm': '2022-09',
     'so2Value': '.003',
     'coValue': '.3',
     'msrstnName': '강남구',
     'pm10Value': '23',
     'no2Value': '.02',
     'o3Value': '.032',
     'pm25Value': '12'},
    {'msurMm': '2022-10',
     'so2Value': '.003',
     'coValue': '.4',
     'msrstnName': '강남구',
     'pm10Value': '26',
     'no2Value': '.024',
     'o3Value': '.024',
     'pm25Value': '14'},
    {'msurMm': '2022-11',
     'so2Value': '.003',
     'coValue': '.5',
     'msrstnName': '강남구',
     'pm10Value': '39',
     'no2Value': '.031',
     'o3Value': '.019',
     'pm25Value': '22'},
    {'msurMm': '2022-12',
     'so2Value': '.003',
     'coValue': '.5',
     'msrstnName': '강남구',
     'pm10Value': '37',
     'no2Value': '.029',
     'o3Value': '.016',
     'pm25Value': '18'},
    {'msurMm': '2023-01',
     'so2Value': '.003',
     'coValue': '.5',
     'msrstnName': '강남구',
     'pm10Value': '46',
     'no2Value': '.031',
     'o3Value': '.017',
     'pm25Value': '25'},
    {'msurMm': '2023-02',
     'so2Value': '.003',
     'coValue': '.5',
     'msrstnName': '강남구',
     'pm10Value': '46',
     'no2Value': '.032',
     'o3Value': '.023',
     'pm25Value': '28'},
    {'msurMm': '2023-03',
     'so2Value': '.003',
     'coValue': '.5',
     'msrstnName': '강남구',
     'pm10Value': '65',
     'no2Value': '.031',
     'o3Value': '.034',
     'pm25Value': '29'},
    {'msurMm': '2023-04',
     'so2Value': '.003',
     'coValue': '.4',
     'msrstnName': '강남구',
     'pm10Value': '60',
     'no2Value': '.02',
     'o3Value': '.04',
     'pm25Value': '19'},
    {'msurMm': '2023-05',
     'so2Value': '.003',
     'coValue': '.3',
     'msrstnName': '강남구',
     'pm10Value': '38',
     'no2Value': '.02',
     'o3Value': '.043',
     'pm25Value': '18'}],
   'pageNo': 1,
   'numOfRows': 100},
  'header': {'resultMsg': 'NORMAL_CODE', 'resultCode': '00'}}}

In [24]:
pd.DataFrame(json.loads(contents)['response']['body']['items'])

     msurMm so2Value coValue msrstnName pm10Value no2Value o3Value pm25Value
0   2022-05     .003      .3        강남구        31     .016    .051        16
1   2022-06     .003      .3        강남구        22     .016    .038        12
2   2022-07     .003      .3        강남구        26     .017    .039        17
3   2022-08     .003      .3        강남구        21     .017    .033        12
4   2022-09     .003      .3        강남구        23      .02    .032        12
5   2022-10     .003      .4        강남구        26     .024    .024        14
6   2022-11     .003      .5        강남구        39     .031    .019        22
7   2022-12     .003      .5        강남구        37     .029    .016        18
8   2023-01     .003      .5        강남구        46     .031    .017        25
9   2023-02     .003      .5        강남구        46     .032    .023        28
10  2023-03     .003      .5        강남구        65     .031    .034        29
11  2023-04     .003      .4        강남구        60      .02     .04        19
12  2023-05     .003      .3        강남구        38      .02    .043        18

In [25]:
# url 입력
yourkey = '1UQZTnyGMC0LoiusOGYLU6SJfaOJXqz2t6ZUUw5ZKDIxOzFGGkhLlW3bHkT5vaShQrUqJrZRPJucnWmszUsVJQ%3D%3D'

url = 'https://apis.data.go.kr/B552584/ArpltnStatsSvc/getMsrstnAcctoRMmrg?serviceKey=1UQZTnyGMC0LoiusOGYLU6SJfaOJXqz2t6ZUUw5ZKDIxOzFGGkhLlW3bHkT5vaShQrUqJrZRPJucnWmszUsVJQ%3D%3D&returnType=json&numOfRows=100&pageNo=1&inqBginMm=202205&inqEndMm=202305&msrstnName=%EA%B5%AC%EB%A1%9C%EA%B5%AC'

# url 불러오기
response = requests.get(url)

#데이터 값 출력해보기
contents = response.text
contents

'{"response":{"body":{"totalCount":13,"items":[{"msurMm":"2022-05","so2Value":".003","coValue":".4","msrstnName":"구로구","pm10Value":"39","no2Value":".014","o3Value":".049","pm25Value":"16"},{"msurMm":"2022-06","so2Value":".002","coValue":".3","msrstnName":"구로구","pm10Value":"22","no2Value":".01","o3Value":".038","pm25Value":"11"},{"msurMm":"2022-07","so2Value":".002","coValue":".3","msrstnName":"구로구","pm10Value":"21","no2Value":".011","o3Value":".039","pm25Value":"12"},{"msurMm":"2022-08","so2Value":".002","coValue":".3","msrstnName":"구로구","pm10Value":"16","no2Value":".011","o3Value":".033","pm25Value":"7"},{"msurMm":"2022-09","so2Value":".002","coValue":".3","msrstnName":"구로구","pm10Value":"26","no2Value":".014","o3Value":".033","pm25Value":"11"},{"msurMm":"2022-10","so2Value":".002","coValue":".4","msrstnName":"구로구","pm10Value":"33","no2Value":".019","o3Value":".024","pm25Value":"16"},{"msurMm":"2022-11","so2Value":".003","coValue":".4","msrstnName":"구로구","pm10Value":"47","no2Value":".026","o3Value":".017","pm25Value":"23"},{"msurMm":"2022-12","so2Value":".003","coValue":".4","msrstnName":"구로구","pm10Value":"40","no2Value":".025","o3Value":".014","pm25Value":"17"},{"msurMm":"2023-01","so2Value":".003","coValue":".4","msrstnName":"구로구","pm10Value":"52","no2Value":".027","o3Value":".014","pm25Value":"25"},{"msurMm":"2023-02","so2Value":".003","coValue":".5","msrstnName":"구로구","pm10Value":"50","no2Value":".027","o3Value":".019","pm25Value":"30"},{"msurMm":"2023-03","so2Value":".003","coValue":".5","msrstnName":"구로구","pm10Value":"79","no2Value":".024","o3Value":".029","pm25Value":"36"},{"msurMm":"2023-04","so2Value":".003","coValue":".4","msrstnName":"구로구","pm10Value":"74","no2Value":".016","o3Value":".036","pm25Value":"23"},{"msurMm":"2023-05","so2Value":".003","coValue":".3","msrstnName":"구로구","pm10Value":"45","no2Value":".014","o3Value":".037","pm25Value":"18"}],"pageNo":1,"numOfRows":100},"header":{"resultMsg":"NORMAL_CODE","resultCode":"00"}}}'

In [26]:
pd.DataFrame(json.loads(contents)['response']['body']['items'])

     msurMm so2Value coValue msrstnName pm10Value no2Value o3Value pm25Value
0   2022-05     .003      .4        구로구        39     .014    .049        16
1   2022-06     .002      .3        구로구        22      .01    .038        11
2   2022-07     .002      .3        구로구        21     .011    .039        12
3   2022-08     .002      .3        구로구        16     .011    .033         7
4   2022-09     .002      .3        구로구        26     .014    .033        11
5   2022-10     .002      .4        구로구        33     .019    .024        16
6   2022-11     .003      .4        구로구        47     .026    .017        23
7   2022-12     .003      .4        구로구        40     .025    .014        17
8   2023-01     .003      .4        구로구        52     .027    .014        25
9   2023-02     .003      .5        구로구        50     .027    .019        30
10  2023-03     .003      .5        구로구        79     .024    .029        36
11  2023-04     .003      .4        구로구        74     .016    .036        23
12  2023-05     .003      .3        구로구        45     .014    .037        18